namespace GeoViewer.View.UI.Dialogue
{
    /// <summary>
    /// The response of the user in the dialogue.
    /// </summary>
    /// <typeparam name="T">the type of the response</typeparam>
    public record DialogueResponse<T>
    {
        /// <summary>
        /// Indicates if the menu produced a successful result.
        /// </summary>
        public DialogueResponseStatus Status { get; }

        /// <summary>
        /// The data generated by the menu based on the interaction between the menu and the user.
        /// Only contains useful data iff. the <see cref="Status"/> is successful.
        /// Otherwise this property contains <c>default(T)</c>, which may be null.
        /// </summary>
        public T? Response { get; }

        /// <summary>
        /// Creates a new dialogue response with the given status und the given response data.
        /// </summary>
        /// <param name="status">the status whether the interaction was successful or not</param>
        /// <param name="response">the data from the interaction</param>
        private DialogueResponse(DialogueResponseStatus status, T? response)
        {
            Status = status;
            Response = response;
        }

        /// <summary>
        /// Creates a new canceled dialogue response.
        /// </summary>
        /// <returns>the created dialogue response</returns>
        public static DialogueResponse<T> Canceled()
        {
            return new DialogueResponse<T>(DialogueResponseStatus.Canceled, default);
        }

        /// <summary>
        /// Creates a new successful dialogue response from the given response data.
        /// </summary>
        /// <param name="response">the response data from the dialogue</param>
        /// <returns>the created dialogue response</returns>
        public static DialogueResponse<T> Success(T response)
        {
            return new DialogueResponse<T>(DialogueResponseStatus.Success, response);
        }
    }
}