using System.Threading.Tasks;

namespace GeoViewer.View.UI.Dialogue
{
    /// <summary>
    /// An abstract class representing a menu which can be opened to get information from the user.
    /// </summary>
    /// <typeparam name="T">The type of object returned when the interaction was successful</typeparam>
    public abstract class Dialogue<T> : UIElement
    {
        /// <summary>
        /// Opens the menu if it isn't already open and starts the interaction with the user.
        /// </summary>
        /// <returns>
        /// A menu result indicating whether or not the interaction was successful.
        /// If the interaction was successful, this contains the data generated by the interaction.
        /// </returns>
        public abstract Task<DialogueResponse<T>> Open();
    }
}